services:
  savage-bot:
    image: mateocallec/savage-bot:latest
    container_name: savage-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - NODE_ENV=production
      - TZ=UTC
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    network_mode: bridge

networks:
  default:
    driver: bridge
